services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
      http.cors.enabled: "true"
      http.port: "9200"
      network.host: "0.0.0.0"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health | grep -q 'status'"]
      interval: 10s
      retries: 20
    volumes:
      - esdata:/usr/share/elasticsearch/data

  api:
    build: .
    container_name: rag_project-api-1
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ES_HOST: "elasticsearch"
      ES_PORT: "9200"
      ES_INDEX: "rag_index"
      EMBEDDING_MODEL: "all-MiniLM-L6-v2"
      MISTRAL_API_KEY: "${MISTRAL_API_KEY}"
      MISTRAL_MODEL: "mistral-small-latest"
    ports:
      - "8000:8000"
    command: ["./wait_for_es.sh", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  esdata:
